### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [jliljebl/flowblade-packaging#1]
Please provide the AppImage for download, e.g., on GitHub Releases, so that it could be included in the AppImageHub central directory of available AppImages. Thank you!

**Comment by jliljebl** [comment]
As soon as I successfully create one, I will.

**Comment by jliljebl** [comment]
We have decided to go Flatpak for the time being.

**Comment by probonopd** [comment]
Thanks, but it's not an either-or, and Flatpak is not a portable app format. So why not have both.

**Comment by jliljebl** [comment]
EDIT. Oh, I wrote a comment that was meant for the PPA issue.

On AppImage the main point is that I just do not wish to spend any more time on packaking Issues, Flatpak is working for us now, has some momentum so we are now staying with it for the time being.

**Comment by probonopd** [comment]
Hi @jliljebl no one is suggesting you should drop the Flatpak. But it is not a replacement for an AppImage. Would you be open to a pull request that would build it on Travis CI?

**Comment by jliljebl** [comment]
Yes, if you have a pull request that gets this going I can pull that and we can see if we get this done.
