### ISSUE TITLE
Offer PPA

### ISSUE THREAD

**Issue by PanderMusubi** [jliljebl/flowblade-packaging#2]
Please offer a PPA such as http://ppa.launchpad.net/team-xbmc/ppa/ubuntu to install the latest version of Flowblade on Ubuntu/Debian and automatically update it.

Instructions should be added to https://jliljebl.github.io/flowblade/download.html and https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/INSTALLING.md

**Comment by jliljebl** [comment]
I consider PPA outdated and too distro specific technology an I do not believe it adds any value over the current offering of .*deb* and Flatpak.

All new offered distribution methods add greatly to maintenance overhead, we are already getting some Flatpak specific bugs and need to get additional information on all bug reports.

**Comment by PanderMusubi** [comment]
Thanks for your elaboration on this. I don't care about the specific form of packaging, only that `apt-get update` can find it. In that way, users don't have manually check if there is a new version and uodate it manually too. So the PPA would only be hosting the architecture-independent .deb file as is (noarch).

**Comment by PanderMusubi** [comment]
There are a lot of users that are not a fan of Flatpak, Snap, etc. If you would like to reconsider, an example for generating and uploading source deb file to Launchpad is in https://github.com/nuspell/misc-nuspell/tree/master/packaging/deb and it would save you the trouble of buiding and hosting them yourself while the end users get automated updates.

Let me know if you need help with it. Launchpad builds binaries for all supported Ubuntu releases for all supported architectures as you can see in e.g. https://launchpad.net/~nuspell/+archive/ubuntu/ppa

I have experience with Debian, Fedora, Flatpak, Snap, Conan, Brew but find Ubuntu Launchpad PPA to work the best without overhead or additional bugs.
